force-app/main/default/objects/Batch_Tracker__c/Batch_Tracker__c.object-meta.xml
<CustomObject>
    <description>This object will active the batch in the org in batch center</description>
    <label>Batch Tracker</label>
    <nameField>
        <label>Batch Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Tracker__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define if the batch is active for the process or not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Tracker__c/fields/End_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Field__c</fullName>
    <description>Holds the end date field will be set to run the batch</description>
    <label>End Date Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Tracker__c/fields/Record_Identifier_Field__c.field-meta.xml
<CustomField>
    <fullName>Record_Identifier_Field__c</fullName>
    <description>This field will be used to re run the batch for specific records in the org</description>
    <inlineHelpText>This field will be used to re run the batch for specific records in the org</inlineHelpText>
    <label>Record Identifier Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Tracker__c/fields/Start_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Field__c</fullName>
    <description>Holds the field used as start date to run the batch</description>
    <label>Start Date Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchTrackerController.cls
public with sharing class BatchTrackerController {
    public BatchTrackerController() {
    }

    @AuraEnabled(cacheable=true)
    public static List<LWCUtility.Field> getBatchesInSystem() {
        List<LWCUtility.Field> batchesList = new List<LWCUtility.Field>();
        //For this solution to work, each batch class has to implement de default constructor
        for (ApexClass c : [SELECT Name FROM ApexClass]) {
            try {
                System.Type t = system.type.forname(c.Name);
                if (t != null && t.newInstance() instanceof Database.Batchable<sObject>) {
                    batchesList.add(new LWCUtility.Field(t.getName(), t.getName()));
                }
            } catch (exception e) {
            }
        }
        System.debug('list batches: ' + batchesList);
        return batchesList;
    }
    @AuraEnabled
    public static List<Batch_Tracker__c> getBatchTrackersList() {
        return [
            SELECT Id, Name, Start_Date_Field__c, End_Date_Field__c, Record_Identifier_Field__c, Active__c
            FROM Batch_Tracker__c
            LIMIT 5000
        ];
    }
}